# Generated by Django 5.2.4 on 2025-07-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=100)),
                ('achternaam', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gsm', models.CharField(blank=True, max_length=20, null=True)),
                ('allergieen', models.TextField(blank=True, null=True)),
                ('haartype', models.CharField(blank=True, max_length=100, null=True)),
                ('natuurlijke_haarkleur', models.CharField(blank=True, max_length=100, null=True)),
                ('toonhoogte', models.CharField(blank=True, max_length=100, null=True)),
                ('weerschijn', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage_witte_haren', models.IntegerField(blank=True, null=True)),
                ('color_formula', models.CharField(blank=True, max_length=200, null=True)),
                ('volledig_adres', models.TextField(blank=True, null=True)),
                ('techniek', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
