# Generated by Django 5.2.4 on 2025-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapperapp', '0002_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klant',
            old_name='toonhoogte',
            new_name='toonhoogte_lengtes',
        ),
        migrations.AddField(
            model_name='klant',
            name='behandeling_hiervoor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='huid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='inwerktijd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='producten',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klant',
            name='wens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
