# Generated by Django 5.2.4 on 2025-07-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapperapp', '0003_rename_toonhoogte_klant_toonhoogte_lengtes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klant',
            old_name='percentage_witte_haren',
            new_name='percentage_witte_haren_achter',
        ),
        migrations.AddField(
            model_name='klant',
            name='percentage_witte_haren_voor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
