# Generated by Django 5.2.4 on 2025-07-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapperapp', '0004_rename_percentage_witte_haren_klant_percentage_witte_haren_achter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klant',
            name='laatste_rekening',
            field=models.TextField(blank=True, null=True),
        ),
    ]
