"""
Django settings for kapperapp project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Current value: Path(__file__).resolve().parent.parent (This correctly evaluates to /home/ubuntu/kapperapp/Kapapp/)
# Ensure it's set to this. It seems you already have this set correctly based on the problem.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kapperapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kapperapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # <-- DIT IS DE CRUCIALE REGEL
        'APP_DIRS': True, # Deze is ook goed om te hebben voor toekomstige apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kapperapp.wsgi.application'
ALLOWED_HOSTS = ['hairapp.be', 'www.hairapp.be', '16.171.138.211']
SECURE_SSL_REDIRECT = True
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default=''), # 'default' ensures it's empty if not set
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Maak een map 'staticfiles' in de root van je project
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'dashboard' # <-- AANGEPAST: Dit is de naam van de URL die we willen redirecten naar na login
LOGIN_URL = 'login' # <-- AANGEPAST: Gebruik hier ook de URL-naam

# HTTPS-instellingen INGESCHAKELD voor productie
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True  # Redirect alle HTTP-verzoeken naar HTTPS
SECURE_HSTS_SECONDS = 31536000 # HSTS ingeschakeld voor 1 jaar (aanbevolen)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True # Geldt ook voor subdomeinen
SECURE_HSTS_PRELOAD = True # Vooraf laden voor betere beveiliging

# Veiligheidsinstellingen voor HTTPS
CSRF_COOKIE_HTTPONLY = True # Zet dit op True voor extra beveiliging in productie
SESSION_COOKIE_HTTPONLY = True # Aanbevolen voor sessiebeveiliging
CSRF_COOKIE_SECURE = True # Zet dit op True voor HTTPS
SESSION_COOKIE_SECURE = True # Zet dit op True voor HTTPS
CSRF_COOKIE_SAMESITE = 'Lax' # Goede balans tussen veiligheid en functionaliteit
SESSION_COOKIE_SAMESITE = 'Lax'

# CSRF_TRUSTED_ORIGINS toevoegen voor HTTPS
CSRF_TRUSTED_ORIGINS = [
    'https://hairapp.be',
    'https://www.hairapp.be',
    'https://16.171.138.211', # Als je nog steeds via IP wilt kunnen testen met HTTPS
]
